// Built-in themes for IDEC
export const themes = {
  'idec-dark': {
    id: 'idec-dark',
    name: 'IDEC Dark',
    type: 'dark',
    colors: {
      background: '#09090b',
      foreground: '#fafafa',
      card: '#0f0f11',
      cardForeground: '#fafafa',
      primary: '#3b82f6',
      primaryForeground: '#ffffff',
      secondary: '#18181b',
      secondaryForeground: '#fafafa',
      muted: '#27272a',
      mutedForeground: '#71717a',
      accent: '#3b82f6',
      accentForeground: '#fafafa',
      destructive: '#ef4444',
      destructiveForeground: '#fafafa',
      border: '#27272a',
      input: '#27272a',
      ring: '#3b82f6',
    },
    editor: {
      background: '#09090b',
      foreground: '#fafafa',
      lineHighlight: '#18181b',
      selection: '#3b82f633',
      cursor: '#3b82f6',
      lineNumber: '#3f3f46',
      lineNumberActive: '#71717a',
      indentGuide: '#27272a',
    },
    syntax: {
      comment: '#6b7280',
      keyword: '#c084fc',
      string: '#86efac',
      number: '#fcd34d',
      function: '#60a5fa',
      variable: '#f9fafb',
      type: '#2dd4bf',
      operator: '#f472b6',
    }
  },
  'idec-light': {
    id: 'idec-light',
    name: 'IDEC Light',
    type: 'light',
    colors: {
      background: '#ffffff',
      foreground: '#09090b',
      card: '#f4f4f5',
      cardForeground: '#09090b',
      primary: '#2563eb',
      primaryForeground: '#ffffff',
      secondary: '#f4f4f5',
      secondaryForeground: '#18181b',
      muted: '#e4e4e7',
      mutedForeground: '#71717a',
      accent: '#2563eb',
      accentForeground: '#ffffff',
      destructive: '#dc2626',
      destructiveForeground: '#ffffff',
      border: '#e4e4e7',
      input: '#e4e4e7',
      ring: '#2563eb',
    },
    editor: {
      background: '#ffffff',
      foreground: '#09090b',
      lineHighlight: '#f4f4f5',
      selection: '#2563eb33',
      cursor: '#2563eb',
      lineNumber: '#a1a1aa',
      lineNumberActive: '#52525b',
      indentGuide: '#e4e4e7',
    },
    syntax: {
      comment: '#6b7280',
      keyword: '#7c3aed',
      string: '#16a34a',
      number: '#d97706',
      function: '#2563eb',
      variable: '#18181b',
      type: '#0891b2',
      operator: '#db2777',
    }
  },
  'monokai': {
    id: 'monokai',
    name: 'Monokai',
    type: 'dark',
    colors: {
      background: '#272822',
      foreground: '#f8f8f2',
      card: '#1e1f1c',
      cardForeground: '#f8f8f2',
      primary: '#a6e22e',
      primaryForeground: '#272822',
      secondary: '#3e3d32',
      secondaryForeground: '#f8f8f2',
      muted: '#3e3d32',
      mutedForeground: '#75715e',
      accent: '#66d9ef',
      accentForeground: '#272822',
      destructive: '#f92672',
      destructiveForeground: '#ffffff',
      border: '#3e3d32',
      input: '#3e3d32',
      ring: '#a6e22e',
    },
    editor: {
      background: '#272822',
      foreground: '#f8f8f2',
      lineHighlight: '#3e3d32',
      selection: '#49483e',
      cursor: '#f8f8f0',
      lineNumber: '#75715e',
      lineNumberActive: '#f8f8f2',
      indentGuide: '#3e3d32',
    },
    syntax: {
      comment: '#75715e',
      keyword: '#f92672',
      string: '#e6db74',
      number: '#ae81ff',
      function: '#a6e22e',
      variable: '#f8f8f2',
      type: '#66d9ef',
      operator: '#f92672',
    }
  },
  'dracula': {
    id: 'dracula',
    name: 'Dracula',
    type: 'dark',
    colors: {
      background: '#282a36',
      foreground: '#f8f8f2',
      card: '#21222c',
      cardForeground: '#f8f8f2',
      primary: '#bd93f9',
      primaryForeground: '#282a36',
      secondary: '#44475a',
      secondaryForeground: '#f8f8f2',
      muted: '#44475a',
      mutedForeground: '#6272a4',
      accent: '#ff79c6',
      accentForeground: '#282a36',
      destructive: '#ff5555',
      destructiveForeground: '#ffffff',
      border: '#44475a',
      input: '#44475a',
      ring: '#bd93f9',
    },
    editor: {
      background: '#282a36',
      foreground: '#f8f8f2',
      lineHighlight: '#44475a',
      selection: '#44475a',
      cursor: '#f8f8f0',
      lineNumber: '#6272a4',
      lineNumberActive: '#f8f8f2',
      indentGuide: '#44475a',
    },
    syntax: {
      comment: '#6272a4',
      keyword: '#ff79c6',
      string: '#f1fa8c',
      number: '#bd93f9',
      function: '#50fa7b',
      variable: '#f8f8f2',
      type: '#8be9fd',
      operator: '#ff79c6',
    }
  },
  'github-dark': {
    id: 'github-dark',
    name: 'GitHub Dark',
    type: 'dark',
    colors: {
      background: '#0d1117',
      foreground: '#c9d1d9',
      card: '#161b22',
      cardForeground: '#c9d1d9',
      primary: '#58a6ff',
      primaryForeground: '#0d1117',
      secondary: '#21262d',
      secondaryForeground: '#c9d1d9',
      muted: '#21262d',
      mutedForeground: '#8b949e',
      accent: '#58a6ff',
      accentForeground: '#0d1117',
      destructive: '#f85149',
      destructiveForeground: '#ffffff',
      border: '#30363d',
      input: '#21262d',
      ring: '#58a6ff',
    },
    editor: {
      background: '#0d1117',
      foreground: '#c9d1d9',
      lineHighlight: '#161b22',
      selection: '#264f78',
      cursor: '#58a6ff',
      lineNumber: '#484f58',
      lineNumberActive: '#c9d1d9',
      indentGuide: '#21262d',
    },
    syntax: {
      comment: '#8b949e',
      keyword: '#ff7b72',
      string: '#a5d6ff',
      number: '#79c0ff',
      function: '#d2a8ff',
      variable: '#c9d1d9',
      type: '#7ee787',
      operator: '#ff7b72',
    }
  },
  'one-dark': {
    id: 'one-dark',
    name: 'One Dark Pro',
    type: 'dark',
    colors: {
      background: '#282c34',
      foreground: '#abb2bf',
      card: '#21252b',
      cardForeground: '#abb2bf',
      primary: '#61afef',
      primaryForeground: '#282c34',
      secondary: '#3a3f4b',
      secondaryForeground: '#abb2bf',
      muted: '#3a3f4b',
      mutedForeground: '#5c6370',
      accent: '#c678dd',
      accentForeground: '#282c34',
      destructive: '#e06c75',
      destructiveForeground: '#ffffff',
      border: '#3a3f4b',
      input: '#3a3f4b',
      ring: '#61afef',
    },
    editor: {
      background: '#282c34',
      foreground: '#abb2bf',
      lineHighlight: '#2c313a',
      selection: '#3e4451',
      cursor: '#528bff',
      lineNumber: '#4b5263',
      lineNumberActive: '#abb2bf',
      indentGuide: '#3a3f4b',
    },
    syntax: {
      comment: '#5c6370',
      keyword: '#c678dd',
      string: '#98c379',
      number: '#d19a66',
      function: '#61afef',
      variable: '#e06c75',
      type: '#e5c07b',
      operator: '#56b6c2',
    }
  },
  'solarized-dark': {
    id: 'solarized-dark',
    name: 'Solarized Dark',
    type: 'dark',
    colors: {
      background: '#002b36',
      foreground: '#839496',
      card: '#073642',
      cardForeground: '#839496',
      primary: '#268bd2',
      primaryForeground: '#fdf6e3',
      secondary: '#073642',
      secondaryForeground: '#839496',
      muted: '#073642',
      mutedForeground: '#586e75',
      accent: '#2aa198',
      accentForeground: '#fdf6e3',
      destructive: '#dc322f',
      destructiveForeground: '#fdf6e3',
      border: '#073642',
      input: '#073642',
      ring: '#268bd2',
    },
    editor: {
      background: '#002b36',
      foreground: '#839496',
      lineHighlight: '#073642',
      selection: '#073642',
      cursor: '#839496',
      lineNumber: '#586e75',
      lineNumberActive: '#93a1a1',
      indentGuide: '#073642',
    },
    syntax: {
      comment: '#586e75',
      keyword: '#859900',
      string: '#2aa198',
      number: '#d33682',
      function: '#268bd2',
      variable: '#b58900',
      type: '#cb4b16',
      operator: '#859900',
    }
  },
  'nord': {
    id: 'nord',
    name: 'Nord',
    type: 'dark',
    colors: {
      background: '#2e3440',
      foreground: '#eceff4',
      card: '#3b4252',
      cardForeground: '#eceff4',
      primary: '#88c0d0',
      primaryForeground: '#2e3440',
      secondary: '#434c5e',
      secondaryForeground: '#eceff4',
      muted: '#434c5e',
      mutedForeground: '#d8dee9',
      accent: '#81a1c1',
      accentForeground: '#2e3440',
      destructive: '#bf616a',
      destructiveForeground: '#eceff4',
      border: '#4c566a',
      input: '#434c5e',
      ring: '#88c0d0',
    },
    editor: {
      background: '#2e3440',
      foreground: '#eceff4',
      lineHighlight: '#3b4252',
      selection: '#434c5e',
      cursor: '#d8dee9',
      lineNumber: '#4c566a',
      lineNumberActive: '#d8dee9',
      indentGuide: '#434c5e',
    },
    syntax: {
      comment: '#616e88',
      keyword: '#81a1c1',
      string: '#a3be8c',
      number: '#b48ead',
      function: '#88c0d0',
      variable: '#d8dee9',
      type: '#8fbcbb',
      operator: '#81a1c1',
    }
  },
  'high-contrast': {
    id: 'high-contrast',
    name: 'High Contrast',
    type: 'dark',
    colors: {
      background: '#000000',
      foreground: '#ffffff',
      card: '#0a0a0a',
      cardForeground: '#ffffff',
      primary: '#00ff00',
      primaryForeground: '#000000',
      secondary: '#1a1a1a',
      secondaryForeground: '#ffffff',
      muted: '#2a2a2a',
      mutedForeground: '#cccccc',
      accent: '#00ffff',
      accentForeground: '#000000',
      destructive: '#ff0000',
      destructiveForeground: '#ffffff',
      border: '#ffffff',
      input: '#1a1a1a',
      ring: '#00ff00',
    },
    editor: {
      background: '#000000',
      foreground: '#ffffff',
      lineHighlight: '#1a1a1a',
      selection: '#264f78',
      cursor: '#ffffff',
      lineNumber: '#888888',
      lineNumberActive: '#ffffff',
      indentGuide: '#333333',
    },
    syntax: {
      comment: '#7ca668',
      keyword: '#569cd6',
      string: '#ce9178',
      number: '#b5cea8',
      function: '#dcdcaa',
      variable: '#9cdcfe',
      type: '#4ec9b0',
      operator: '#d4d4d4',
    }
  },
};

// Convert theme to Monaco editor theme
export function createMonacoTheme(theme) {
  return {
    base: theme.type === 'light' ? 'vs' : 'vs-dark',
    inherit: true,
    rules: [
      { token: 'comment', foreground: theme.syntax.comment.replace('#', ''), fontStyle: 'italic' },
      { token: 'keyword', foreground: theme.syntax.keyword.replace('#', '') },
      { token: 'string', foreground: theme.syntax.string.replace('#', '') },
      { token: 'number', foreground: theme.syntax.number.replace('#', '') },
      { token: 'function', foreground: theme.syntax.function.replace('#', '') },
      { token: 'variable', foreground: theme.syntax.variable.replace('#', '') },
      { token: 'type', foreground: theme.syntax.type.replace('#', '') },
      { token: 'operator', foreground: theme.syntax.operator.replace('#', '') },
    ],
    colors: {
      'editor.background': theme.editor.background,
      'editor.foreground': theme.editor.foreground,
      'editor.lineHighlightBackground': theme.editor.lineHighlight,
      'editor.lineHighlightBorder': '#00000000',
      'editorCursor.foreground': theme.editor.cursor,
      'editor.selectionBackground': theme.editor.selection,
      'editorLineNumber.foreground': theme.editor.lineNumber,
      'editorLineNumber.activeForeground': theme.editor.lineNumberActive,
      'editorIndentGuide.background': theme.editor.indentGuide,
      'scrollbarSlider.background': theme.colors.muted + '80',
      'editorWidget.background': theme.colors.card,
      'editorWidget.border': theme.colors.border,
    }
  };
}

// Apply theme to CSS variables
export function applyTheme(theme) {
  const root = document.documentElement;
  const colors = theme.colors;
  
  root.style.setProperty('--background', colors.background);
  root.style.setProperty('--foreground', colors.foreground);
  root.style.setProperty('--card', colors.card);
  root.style.setProperty('--card-foreground', colors.cardForeground);
  root.style.setProperty('--primary', colors.primary);
  root.style.setProperty('--primary-foreground', colors.primaryForeground);
  root.style.setProperty('--secondary', colors.secondary);
  root.style.setProperty('--secondary-foreground', colors.secondaryForeground);
  root.style.setProperty('--muted', colors.muted);
  root.style.setProperty('--muted-foreground', colors.mutedForeground);
  root.style.setProperty('--accent', colors.accent);
  root.style.setProperty('--accent-foreground', colors.accentForeground);
  root.style.setProperty('--destructive', colors.destructive);
  root.style.setProperty('--destructive-foreground', colors.destructiveForeground);
  root.style.setProperty('--border', colors.border);
  root.style.setProperty('--input', colors.input);
  root.style.setProperty('--ring', colors.ring);
}

export default themes;
